# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparcraft.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sparcraft.proto',
  package='sparcraft',
  syntax='proto3',
  serialized_pb=_b('\n\x0fsparcraft.proto\x12\tsparcraft\"_\n\x08\x66\x65\x61tures\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02hp\x18\x02 \x01(\x05\x12\x0c\n\x04posx\x18\x03 \x01(\x05\x12\x0c\n\x04posy\x18\x04 \x01(\x05\x12\x0e\n\x06\x65nergy\x18\x05 \x01(\x05\x12\x0f\n\x07shields\x18\x06 \x01(\x05\")\n\x04\x41rmy\x12!\n\x04unit\x18\x32 \x03(\x0b\x32\x13.sparcraft.featuresb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FEATURES = _descriptor.Descriptor(
  name='features',
  full_name='sparcraft.features',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sparcraft.features.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='sparcraft.features.hp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posx', full_name='sparcraft.features.posx', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posy', full_name='sparcraft.features.posy', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='energy', full_name='sparcraft.features.energy', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shields', full_name='sparcraft.features.shields', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=125,
)


_ARMY = _descriptor.Descriptor(
  name='Army',
  full_name='sparcraft.Army',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unit', full_name='sparcraft.Army.unit', index=0,
      number=50, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=168,
)

_ARMY.fields_by_name['unit'].message_type = _FEATURES
DESCRIPTOR.message_types_by_name['features'] = _FEATURES
DESCRIPTOR.message_types_by_name['Army'] = _ARMY

features = _reflection.GeneratedProtocolMessageType('features', (_message.Message,), dict(
  DESCRIPTOR = _FEATURES,
  __module__ = 'sparcraft_pb2'
  # @@protoc_insertion_point(class_scope:sparcraft.features)
  ))
_sym_db.RegisterMessage(features)

Army = _reflection.GeneratedProtocolMessageType('Army', (_message.Message,), dict(
  DESCRIPTOR = _ARMY,
  __module__ = 'sparcraft_pb2'
  # @@protoc_insertion_point(class_scope:sparcraft.Army)
  ))
_sym_db.RegisterMessage(Army)


# @@protoc_insertion_point(module_scope)
